import { Component } from "solid-js";

const CatalystTab: Component = () => {
  return (
    <div class="guide-tab-content">
      <div class="guide-card guide-card-draft">
        <div class="guide-card-body">
          This content is autogenerated placeholder data. It will be replaced with a proper multi-agent setup guide in a future update.
        </div>
      </div>
      <div class="guide-card guide-card-accent">
        <div class="guide-card-title">What is a Multi-Agent Factory?</div>
        <div class="guide-card-body">
          A multi-agent factory is an environment where multiple AI agents work in parallel on the same codebase, coordinated by a file-based messaging system. Agents communicate with each other, split tasks, and escalate to the human only when necessary.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">1. Define your team</div>
        <div class="guide-card-body">
          Go to your project's .ac-new/ directory and create a team via _team_*/config.json. Define agents, a coordinator, and repos. Teams are discovered automatically from these config files.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">2. Prepare the repo</div>
        <div class="guide-card-body">
          Each agent works on its own branch. Make sure the repo has a CLAUDE.md (or equivalent) with the project instructions. This is what guides each agent on how to work.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">3. Launch the agents</div>
        <div class="guide-card-body">
          Open a session per agent using "Open Agent". Each session starts in the repo directory. Give each agent its initial prompt describing its specific task. Agents communicate via the inter-agent messaging system.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">4. Monitor and orchestrate</div>
        <div class="guide-card-body">
          Use the sidebar to see each agent's status. Indicators show whether an agent is working or waiting for input. Switch between sessions to see each agent's output in real time.
        </div>
      </div>
    </div>
  );
};

export default CatalystTab;
