import { Component } from "solid-js";

const CatalystTab: Component = () => {
  return (
    <div class="guide-tab-content">
      <div class="guide-card guide-card-draft">
        <div class="guide-card-body">
          This content is autogenerated placeholder data. It will be replaced with a proper Dark Factory setup guide in a future update.
        </div>
      </div>
      <div class="guide-card guide-card-accent">
        <div class="guide-card-title">What is a Dark Factory?</div>
        <div class="guide-card-body">
          A Dark Factory is an environment where multiple AI agents work in parallel on the same codebase, coordinated by a file-based messaging system. Agents communicate with each other, split tasks, and escalate to the human only when necessary.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">1. Define your team</div>
        <div class="guide-card-body">
          Go to Settings and configure at least two agents (e.g. Claude + Codex). Then create a Team in the Dark Factory section with clear roles for each agent. Example: one agent for backend, another for frontend, another for tests.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">2. Prepare the repo</div>
        <div class="guide-card-body">
          Each agent works on its own branch. Make sure the repo has a CLAUDE.md (or equivalent) with the project instructions. This is what guides each agent on how to work.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">3. Launch the factory</div>
        <div class="guide-card-body">
          Open a session per agent using "Open Agent". Each session starts in the repo directory. Give each agent its initial prompt describing its specific task. Agents communicate via files in the project directory.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">4. Monitor and orchestrate</div>
        <div class="guide-card-body">
          Use the sidebar to see each agent's status. Indicators show whether an agent is working or waiting for input. Switch between sessions to see each agent's output in real time.
        </div>
      </div>
    </div>
  );
};

export default CatalystTab;
