import { Component } from "solid-js";

const TutorialTab: Component = () => {
  return (
    <div class="guide-tab-content">
      <div class="guide-card guide-card-draft">
        <div class="guide-card-body">
          This content is autogenerated placeholder data. It will be replaced with curated tutorials in a future update.
        </div>
      </div>
      <div class="guide-card">
        <div class="guide-card-title">Welcome to Agents Commander</div>
        <div class="guide-card-body">
          Agents Commander is a terminal session manager with two synchronized windows: the Sidebar (session list) and the Terminal (PTY output via xterm.js).
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">Creating a session</div>
        <div class="guide-card-body">
          Use the "Open Agent" button in the sidebar to launch an AI agent (Claude Code, Codex, or custom) in a directory of your choice. Each session is an independent PTY process.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">Navigating sessions</div>
        <div class="guide-card-body">
          Click any session in the sidebar to activate it. The terminal instantly switches to that session's output. Use Ctrl+Tab / Ctrl+Shift+Tab to cycle between sessions with the keyboard.
        </div>
      </div>

      <div class="guide-card">
        <div class="guide-card-title">Detach and multitask</div>
        <div class="guide-card-body">
          Right-click a session and select "Detach" to open it in its own window. This lets you view multiple terminals simultaneously.
        </div>
      </div>
    </div>
  );
};

export default TutorialTab;
